### ISSUE TITLE
Problem with GTOPO30.tif

### ISSUE THREAD

**Issue by mauriciovancine** [vdicolab/hsdm#3]
Dear, there is a problem with the file 'GTOPO30.tif'.

Can you upload the file again?

Thank you.

--
Maurício Vancine.

**Comment by vdicolab** [comment]
Dear Mauricio,
The file could not be uploaded to Github because it was too big. I would recommend you to download the dataset from : https://lta.cr.usgs.gov/GTOPO30 ,which is where we got it from.
Best regards,
Valeria

**Comment by mauriciovancine** [comment]
Dear Valeria,
Thank you so much for your response.
I will do the download in the page.
Best regards,
Mauricio.
